<?php

use Illuminate\Database\Seeder;
use App\Models\User;
use App\Models\Address;

class DatabaseSeeder extends Seeder
{
    public function run()
    {
        $users = [
            [
                'nome' => 'João Silva',
                'cpf' => '123.456.789-00',
                'data_nascimento' => '1985-05-10',
                'email' => 'joao.silva@example.com',
                'telefone' => '(11) 91234-5678',
                'cep' => '12345-678',
                'estado' => 'SP',
                'cidade' => 'São Paulo',
                'bairro' => 'Centro',
                'endereco' => 'Rua Exemplo',
                'numero' => '123',
                'status' => 1
            ],
            [
                'nome' => 'Maria Souza',
                'cpf' => '234.567.890-11',
                'data_nascimento' => '1990-08-22',
                'email' => 'maria.souza@example.com',
                'telefone' => '(21) 92345-6789',
                'cep' => '12345-678',
                'estado' => 'SP',
                'cidade' => 'São Paulo',
                'bairro' => 'Centro',
                'endereco' => 'Rua Exemplo',
                'numero' => '456',
                'status' => 1
            ],
            [
                'nome' => 'Carlos Pereira',
                'cpf' => '345.678.901-22',
                'data_nascimento' => '1978-12-15',
                'email' => 'carlos.pereira@example.com',
                'telefone' => '(31) 93456-7890',
                'cep' => '12345-678',
                'estado' => 'MG',
                'cidade' => 'Belo Horizonte',
                'bairro' => 'Centro',
                'endereco' => 'Rua Exemplo',
                'numero' => '78',
                'status' => 1
            ],
            [
                'nome' => 'Ana Oliveira',
                'cpf' => '456.789.012-33',
                'data_nascimento' => '1983-03-30',
                'email' => 'ana.oliveira@example.com',
                'telefone' => '(41) 94567-8901',
                'cep' => '12345-678',
                'estado' => 'MG',
                'cidade' => 'Belo Horizonte',
                'bairro' => 'Centro',
                'endereco' => 'Rua Exemplo',
                'numero' => '12',
                'status' => 1
            ],
            [
                'nome' => 'Pedro Lima',
                'cpf' => '567.890.123-44',
                'data_nascimento' => '1995-11-05',
                'email' => 'pedro.lima@example.com',
                'telefone' => '(51) 95678-9012',
                'cep' => '12345-678',
                'estado' => 'RJ',
                'cidade' => 'Rio de Janeiro',
                'bairro' => 'Centro',
                'endereco' => 'Rua Exemplo, 123',
                'numero' => '987',
                'status' => 1
            ],
            [
                'nome' => 'Maria Oliveira',
                'cpf' => '987.654.321-00',
                'data_nascimento' => '1990-08-15',
                'email' => 'maria.oliveira@example.com',
                'telefone' => '(21) 98765-4321',
                'cep' => '22041-001',
                'estado' => 'RJ',
                'cidade' => 'Rio de Janeiro',
                'bairro' => 'Copacabana',
                'endereco' => 'Avenida Atlântica',
                'numero' => '456',
                'status' => 1
            ],
            [
                'nome' => 'Pedro Santos',
                'cpf' => '321.654.987-00',
                'data_nascimento' => '1982-11-23',
                'email' => 'pedro.santos@example.com',
                'telefone' => '(71) 91234-5678',
                'cep' => '40150-001',
                'estado' => 'BA',
                'cidade' => 'Salvador',
                'bairro' => 'Barra',
                'endereco' => 'Rua Marques de Caravelas',
                'numero' => '789',
                'status' => 1
            ],
            [
                'nome' => 'Ana Pereira',
                'cpf' => '456.789.123-00',
                'data_nascimento' => '1979-03-05',
                'email' => 'ana.pereira@example.com',
                'telefone' => '(31) 98765-4321',
                'cep' => '30140-001',
                'estado' => 'MG',
                'cidade' => 'Belo Horizonte',
                'bairro' => 'Savassi',
                'endereco' => 'Rua Pernambuco',
                'numero' => '321',
                'status' => 1
            ],
            [
                'nome' => 'Beatriz Souza',
                'cpf' => '789.123.456-00',
                'data_nascimento' => '1993-09-12',
                'email' => 'beatriz.souza@example.com',
                'telefone' => '(51) 99876-5432',
                'cep' => '90010-000',
                'estado' => 'RS',
                'cidade' => 'Porto Alegre',
                'bairro' => 'Moinhos de Vento',
                'endereco' => 'Rua Padre Chagas',
                'numero' => '987',
                'status' => 1
            ],
            [
                'nome' => 'Lucas Fernandes',
                'cpf' => '159.753.486-20',
                'data_nascimento' => '1988-02-14',
                'email' => 'lucas.fernandes@example.com',
                'telefone' => '(62) 91234-5678',
                'cep' => '74000-001',
                'estado' => 'GO',
                'cidade' => 'Goiânia',
                'bairro' => 'Setor Central',
                'endereco' => 'Avenida Goiás',
                'numero' => '321',
                'status' => 1
            ],
            [
                'nome' => 'Fernanda Lima',
                'cpf' => '963.852.741-30',
                'data_nascimento' => '1995-12-25',
                'email' => 'fernanda.lima@example.com',
                'telefone' => '(84) 98765-4321',
                'cep' => '59010-001',
                'estado' => 'RN',
                'cidade' => 'Natal',
                'bairro' => 'Ponta Negra',
                'endereco' => 'Rua Praia de Pipa',
                'numero' => '654',
                'status' => 1
            ],
            [
                'nome' => 'Rafael Costa',
                'cpf' => '852.963.147-00',
                'data_nascimento' => '1970-07-09',
                'email' => 'rafael.costa@example.com',
                'telefone' => '(48) 92345-6789',
                'cep' => '88010-001',
                'estado' => 'SC',
                'cidade' => 'Florianópolis',
                'bairro' => 'Centro',
                'endereco' => 'Rua Felipe Schmidt',
                'numero' => '987',
                'status' => 1
            ],
            [
                'nome' => 'Mariana Santos',
                'cpf' => '741.258.963-00',
                'data_nascimento' => '1983-04-11',
                'email' => 'mariana.santos@example.com',
                'telefone' => '(91) 99876-5432',
                'cep' => '66010-010',
                'estado' => 'PA',
                'cidade' => 'Belém',
                'bairro' => 'Nazaré',
                'endereco' => 'Avenida Nazaré',
                'numero' => '654',
                'status' => 1
            ],
            [
                'nome' => 'Guilherme Rocha',
                'cpf' => '123.789.456-10',
                'data_nascimento' => '1992-11-30',
                'email' => 'guilherme.rocha@example.com',
                'telefone' => '(82) 91234-5678',
                'cep' => '57010-001',
                'estado' => 'AL',
                'cidade' => 'Maceió',
                'bairro' => 'Pajuçara',
                'endereco' => 'Avenida Doutor Antônio Gouveia',
                'numero' => '321',
                'status' => 1
            ],
            [
                'nome' => 'Júlia Martins',
                'cpf' => '321.654.987-01',
                'data_nascimento' => '1987-10-20',
                'email' => 'julia.martins@example.com',
                'telefone' => '(61) 91234-5678',
                'cep' => '70740-000',
                'estado' => 'DF',
                'cidade' => 'Brasília',
                'bairro' => 'Asa Norte',
                'endereco' => 'Quadra 102',
                'numero' => '456',
                'status' => 1
            ],
            [
                'nome' => 'Rogério Almeida',
                'cpf' => '147.258.369-12',
                'data_nascimento' => '1991-04-08',
                'email' => 'rogerio.almeida@example.com',
                'telefone' => '(41) 92345-6789',
                'cep' => '82010-000',
                'estado' => 'PR',
                'cidade' => 'Curitiba',
                'bairro' => 'Bigorrilho',
                'endereco' => 'Rua Professor Pedro Viriato Parigot de Souza',
                'numero' => '789',
                'status' => 1
            ],
            [
                'nome' => 'Patrícia Ferreira',
                'cpf' => '963.741.852-03',
                'data_nascimento' => '1984-05-17',
                'email' => 'patricia.ferreira@example.com',
                'telefone' => '(11) 94321-6789',
                'cep' => '05501-000',
                'estado' => 'SP',
                'cidade' => 'São Paulo',
                'bairro' => 'Vila Madalena',
                'endereco' => 'Rua Aspicuelta',
                'numero' => '321',
                'status' => 1
            ],
            [
                'nome' => 'Henrique Lima',
                'cpf' => '258.369.147-09',
                'data_nascimento' => '1989-12-02',
                'email' => 'henrique.lima@example.com',
                'telefone' => '(85) 91234-5678',
                'cep' => '60160-000',
                'estado' => 'CE',
                'cidade' => 'Fortaleza',
                'bairro' => 'Aldeota',
                'endereco' => 'Avenida Dom Luís',
                'numero' => '654',
                'status' => 1
            ],
            [
                'nome' => 'Sofia Costa',
                'cpf' => '741.852.963-14',
                'data_nascimento' => '1994-01-30',
                'email' => 'sofia.costa@example.com',
                'telefone' => '(27) 98765-4321',
                'cep' => '29050-000',
                'estado' => 'ES',
                'cidade' => 'Vitória',
                'bairro' => 'Praia do Canto',
                'endereco' => 'Avenida Joaquim Lírio',
                'numero' => '987',
                'status' => 1
            ],
            [
                'nome' => 'Carlos Almeida',
                'cpf' => '112.233.445-56',
                'data_nascimento' => '1982-03-22',
                'email' => 'carlos.almeida@example.com',
                'telefone' => '(31) 91234-5678',
                'cep' => '30110-000',
                'estado' => 'MG',
                'cidade' => 'Belo Horizonte',
                'bairro' => 'Centro',
                'endereco' => 'Rua da Bahia',
                'numero' => '456',
                'status' => 1
            ],
            [
                'nome' => 'Ana Paula Rocha',
                'cpf' => '234.567.890-12',
                'data_nascimento' => '1989-06-15',
                'email' => 'ana.paula.rocha@example.com',
                'telefone' => '(71) 92345-6789',
                'cep' => '40130-000',
                'estado' => 'BA',
                'cidade' => 'Salvador',
                'bairro' => 'Barra',
                'endereco' => 'Avenida Sete de Setembro',
                'numero' => '789',
                'status' => 1
            ],
            [
                'nome' => 'Eduardo Silva',
                'cpf' => '345.678.901-23',
                'data_nascimento' => '1990-09-18',
                'email' => 'eduardo.silva@example.com',
                'telefone' => '(21) 98765-4321',
                'cep' => '22250-000',
                'estado' => 'RJ',
                'cidade' => 'Rio de Janeiro',
                'bairro' => 'Copacabana',
                'endereco' => 'Rua Barata Ribeiro',
                'numero' => '123',
                'status' => 1
            ],
            [
                'nome' => 'Mariana Oliveira',
                'cpf' => '456.789.012-34',
                'data_nascimento' => '1992-11-05',
                'email' => 'mariana.oliveira@example.com',
                'telefone' => '(62) 93123-4567',
                'cep' => '74010-010',
                'estado' => 'GO',
                'cidade' => 'Goiânia',
                'bairro' => 'Setor Bueno',
                'endereco' => 'Avenida T-9',
                'numero' => '654',
                'status' => 1
            ],
            [
                'nome' => 'Roberto Martins',
                'cpf' => '567.890.123-45',
                'data_nascimento' => '1981-08-26',
                'email' => 'roberto.martins@example.com',
                'telefone' => '(92) 91234-5678',
                'cep' => '69000-000',
                'estado' => 'AM',
                'cidade' => 'Manaus',
                'bairro' => 'Centro',
                'endereco' => 'Avenida Eduardo Ribeiro',
                'numero' => '321',
                'status' => 1
            ]
        ];

        foreach ($users as $userData) {
            User::create($userData);
        }
    }
}
