version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: lara-docker-app
    container_name: lara_docker_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./storage:/var/www/storage
    networks:
      - app-network
    environment:
      - PHP_EXTENSION=pdo_mysql
      - PHP_MEMORY_LIMIT=512M
    ports:
      - "9000:9000"

  webserver:
    image: nginx:alpine
    container_name: lara_docker_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app-network

  db:
    image: mysql:5.7
    container_name: lara_docker_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: laraveluser
      MYSQL_PASSWORD: secret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local
